Implement Tests and CI integration
instrumentisto/composer-platform-generator pull request #2
Opened 2019-03-06 10:38 UTC by targs08

Implement Tests and CI travis configuration

2019-03-06 13:31 UTC, targs08 commented
FCM 

```
Implement Unit test and Travis CI Integration (#2)

Additionally:
- refactor UpdatePlatformReqsCommand class
- update README.md
```

2019-03-07 09:15 UTC, tyranron requested changes
@targs08 I've made some corrections (PSR code style, EditorConfig rules, PHP docs), consider them carefully.

Unit tests are not bad, but what we really need here is at least one E2E test, where we check if `config.platform` section for `composer.json` is filled up and contains all the environment packages (no sense to check versions). This will save us from regressions, not unit tests.

2019-03-07 09:15 UTC, tyranron commented on phpunit.xml.dist
> +<phpunit>
@targs08 for `.xml` EditorConfig rules should be added

2019-03-08 13:44 UTC, tyranron approved these changes

2019-03-11 05:32 UTC, merged